name: call_log_fetcher
description: Fetch Android call logs within a specified date range. Intended for enterprise and internal applications.
version: 0.0.1

homepage: https://github.com/sharathjoiskp/call_log_fetcher
repository: https://github.com/sharathjoiskp/call_log_fetcher
issue_tracker: https://github.com/sharathjoiskp/call_log_fetcher/issues

topics:
  - android
  - call-log
  - enterprise
  - crm

environment:
  sdk: ^3.11.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jois.call_log_fetcher
        pluginClass: CallLogFetcherPlugin